#!/usr/bin/env bash

set -e

echo "Installing Kahlan examples -----------------------------------------------------"
echo
"${BASH_SOURCE%/*}/kahlan/install"
echo

echo "Installing Peridot examples ----------------------------------------------------"
echo
"${BASH_SOURCE%/*}/peridot/install"
echo

echo "Installing Pho examples --------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/pho/install"
echo

echo "Installing PHPUnit examples ----------------------------------------------------"
echo
"${BASH_SOURCE%/*}/phpunit/install"
echo
