#!/usr/bin/env bash

set -e

echo "Kahlan examples ----------------------------------------------------------------"
"${BASH_SOURCE%/*}/kahlan/run"
echo

echo "PHPUnit examples ---------------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/phpunit/run"
echo
