#!/usr/bin/env bash

set -e

EXAMPLE="event-emitter"
echo "Event emitter examples ========================================================="
echo

echo "Kahlan example -----------------------------------------------------------------"
"${BASH_SOURCE%/*}/$EXAMPLE/kahlan/run"
echo

echo "PHPUnit example ----------------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/$EXAMPLE/phpunit/run"
echo
