#!/usr/bin/env bash

set -e

echo "Kahlan examples ----------------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/kahlan/run"
echo

echo "Peridot examples ----------------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/peridot/run"
echo

echo "Pho examples -------------------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/pho/run"
echo

echo "PHPUnit examples ---------------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/phpunit/run"
echo

echo "SimpleTest examples ------------------------------------------------------------"
echo
"${BASH_SOURCE%/*}/simpletest/run"
echo
