language: php

matrix:
    include:
        - php: 7.1

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --ignore-platform-reqs
script: make examples

cache:
    directories:
        - $HOME/.composer

sudo: false
