name: Examples
on:
  push:
  pull_request:
  schedule:
  - cron: 0 14 * * 0 # Sunday 2PM UTC = Monday 12AM AEST
jobs:
  test:
    runs-on: ubuntu-latest
    name: PHP 7.4
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '7.4'
        extension-csv: mbstring
        coverage: none
    - name: Check PHP version
      run: php -v
    - name: Install dependencies
      run: make ci-install
    - name: Make
      run: make ci
